import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/guardrails-overview' },
      items: [
        'guides/guardrails-overview',
        'guides/invariant-guard-matrix',
        'guides/lint-rules',
        'guides/boundaries-and-config',
        'guides/hooks-and-ci',
        'guides/consumer-api',
        'guides/row-source-updates',
        'guides/plugin-authoring',
        'guides/edit-extension-flow',
      ],
    },
  ],
  architectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],
  adrSidebar: [
    {
      type: 'autogenerated',
      dirName: 'adr',
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
